language: node_js
node_js:
  - "7"

before_install:
- openssl aes-256-cbc -K $encrypted_e6ed02e79e8a_key -iv $encrypted_e6ed02e79e8a_iv
  -in secrets.tar.enc -out secrets.tar -d

before_script:
- npm install -g gulp-cli
- cd source
- npm install gulp --save-dev
script:
- npm install
- gulp dev-init

before_deploy:
- ssh-add wmb-lights-data.key
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
